const cardSets = [
	'Set',
	'Alternate Art Promos',
	'Ancient Origins',
	'Aquapolis',
	'Arceus',
	'Astral Radiance',
	'Base',
	'Base Set 1st Edition',
	'Base Set 2',
	'Base Set Shadowless',
	'Base Set Unlimited',
	'Battle Styles',
	'Black & White',
	'Black and White Promos',
	'Boundaries Crossed',
	'BREAKpoint',
	'BREAKthrough',
	'Brilliant Stars',
	'Burning Shadows',
	'Call of Legends',
	'Celebrations',
	'Celebrations: Classic Collection',
	'Celestial Storm',
	"Champion's Path",
	'Chilling Reign',
	'complex',
	'Cosmic Eclipse',
	'Crimson Invasion',
	'Crown Zenith',
	'Dark Explorers',
	'Darkness Ablaze',
	'Deoxys',
	'Detective Pikachu',
	'Diamond & Pearl',
	'Diamond and Pearl Promo',
	'Double Crisis',
	'Dragon',
	'Dragon Frontiers',
	'Dragon Majesty',
	'Dragon Vault',
	'Emerald',
	'Emerging Powers',
	'Evolutions',
	'Evolving Skies',
	'Expedition',
	'Fates Collide',
	'Fire Red Leaf Green',
	'Flashfire',
	'Forbidden Light',
	'Fossil',
	'Fossil 1st Edition',
	'Fusion Strike',
	'Generations',
	'Generations Radiant Collection',
	'Great Encounters',
	'Guardians Rising',
	'Gym',
	'Gym Challenge',
	'Gym Challenge 1st Edition',
	'Gym Heroes',
	'Gym Heroes 1st Edition',
	'HeartGold SoulSilver',
	'Hidden Fates',
	'Hidden Legends',
	'HGSS Black Star Promo',
	'Holon Phantoms',
	'Jungle',
	'Jungle 1st Edition',
	'Legend Maker',
	'Legendary Collection',
	'Legendary Treasures',
	'Legendary Treasures Radiant Collection',
	'Legends Awakened',
	'Lost Origin',
	'Lost Thunder',
	'Majestic Dawn',
	"McDonald's 25th Anniversary",
	"McDonald's Promos 2011",
	"McDonald's Promos 2012",
	"McDonald's Promos 2014",
	"McDonald's Promos 2015",
	"McDonald's Promos 2016",
	"McDonald's Promos 2017",
	"McDonald's Promos 2018",
	"McDonald's Promos 2019",
	"McDonald's Promos 2022",
	"McDonald's Promos 2023",
	'Miscellaneous Promos',
	'Mysterious Treasures',
	'Neo',
	'Neo Destiny',
	'Neo Destiny 1st Edition',
	'Neo Discovery',
	'Neo Discovery 1st Edition',
	'Neo Genesis',
	'Neo Genesis 1st Edition',
	'Neo Revelation',
	'Neo Revelation 1st Edition',
	'Nintendo Black Star Promo',
	'Noble Victories',
	'Obsidian Flames',
	'Paldea Evolved',
	'Paldean Fates',
	'Phantom Forces',
	'Plasma Blast',
	'Plasma Freeze',
	'Plasma Storm',
	'Platinum',
	'Pokemon Card 151',
	'Pokemon GO',
	'Pokemon Rumble',
	'Pop Series 1',
	'Pop Series 2',
	'Pop Series 3',
	'Pop Series 4',
	'Pop Series 5',
	'Pop Series 6',
	'Pop Series 7',
	'Pop Series 8',
	'Pop Series 9',
	'Primal Clash',
	'Rebel Clash',
	'Roaring Skies',
	'Ruby and Sapphire',
	'Sandstorm',
	'Scarlet & Violet',
	'Scarlet & Violet Base',
	'Scarlet & Violet Promos',
	'Secret Wonders',
	'Shining Fates',
	'Shining Legends',
	'Shrouded Fable',
	'Silver Tempest',
	'Skyridge',
	'Southern Islands',
	'Steam Siege',
	'Stellar Crown',
	'Stormfront',
	'Sun & Moon',
	'Sun & Moon Black Star Promo',
	'Supreme Victors',
	'Sword & Shield',
	'Sword & Shield Promo',
	'Team Magma vs Team Aqua',
	'Team Rocket',
	'Team Rocket 1st Edition',
	'Team Rocket Returns',
	'Unified Minds',
	'Unseen Forces',
	'Vivid Voltage',
	'XY',
	'XY Promos',
	'XY: Kalos Starter Set',
	'XY: Trainer Kit',
	'XY: Trainer Kit Bisharp & Wigglytuff',
	'XY: Trainer Kit Latias & Latios',
	'XY: Trainer Kit Pikachu Libre & Suicune',
	'XY: Trainer Kit Sylveon & Noivern',
	'XY: Trainer Kit Zygarde',
	'Zero Gravity Collection',
];

export default cardSets;
